image: sphinxdoc/sphinx:4.5.0

stages:
  - build
  - deploy

Build:
  stage: build
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - "build/html/*"
    expire_in: 1 day
  script:
    - make html

Deploy at doc.proxyos.dev:
  stage: deploy
  dependencies: ['Build']
  tags: ['proxyos-server']
  script: deploy-site doc.proxyos.dev build/html
  only:
    - master

